language: php
php:
- 5.6
- 7.0
- 7.1
- hhvm

sudo: false
 
install: 
  - composer self-update
  - composer install --no-interaction --prefer-source
  
script:
  - php vendor/bin/phpunit -c phpunit.xml 

after_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'
   